import { expect, it } from 'vitest';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { JourneyExplorer, PrepareDemo, RememberDemo, RoleplayDemo } from '@/components/journey';
import { AnnualCalculator, BookingCalculator } from '@/components/calculators';
import { LearnerPlatform } from '@/components/illustrations';
import { NextSteps } from '@/components/executive-sections';
import { SourceButton, SourceProvider, SourcesButton } from '@/components/sources';

it('keeps character roleplay separate from evaluation, including difficulty changes', async () => {
  const user=userEvent.setup();
  render(<RoleplayDemo />);
  expect(screen.getByText(/Every time I start something/)).toBeTruthy();
  expect(screen.queryByRole('button',{name:/View example feedback/})).toBeNull();
  await user.click(screen.getByRole('button',{name:'Challenging'}));
  expect(screen.queryByText(/Every time I start something/)).toBeNull();
  expect(screen.getByText(/nobody notices how much/)).toBeTruthy();
  await user.click(screen.getByRole('button',{name:/End scenario/}));
  expect(screen.getByText('Simulation ended')).toBeTruthy();
  expect(screen.queryByText('One strength. One next step.')).toBeNull();
  await user.click(screen.getByRole('button',{name:/View example feedback/}));
  expect(screen.getByText('One strength. One next step.')).toBeTruthy();
  expect(screen.getByText(/This short opening gives limited evidence/)).toBeTruthy();
  await user.click(screen.getByRole('button',{name:/Practise again/}));
  expect(screen.queryByText('One strength. One next step.')).toBeNull();
});
it('turns the notification into a question with response-specific feedback', async () => {
  const user=userEvent.setup();
  render(<RememberDemo />);
  expect(screen.queryByRole('group',{name:/Choose a conversation/})).toBeNull();
  await user.click(screen.getByRole('button',{name:/Open the refresher/}));
  const choices=within(screen.getByRole('group',{name:/Choose a conversation/})).getAllByRole('button');
  await user.click(choices[0]);
  expect(screen.getByRole('status').textContent).toContain('verdict');
  await user.click(choices[1]);
  expect(screen.getByRole('status').textContent).toContain('invites their perspective');
  await user.click(choices[2]);
  expect(screen.getByRole('status').textContent).toContain('accusatory');
  await user.click(screen.getByRole('button',{name:/Reset/}));
  expect(screen.queryByRole('status')).toBeNull();
});
it('requires an explicit choice before previewing shared preparation', async () => {
  const user=userEvent.setup();
  render(<PrepareDemo />);
  const choice=screen.getByRole('checkbox') as HTMLInputElement;
  expect(choice.checked).toBe(false);
  await user.selectOptions(screen.getByLabelText('What makes it difficult?'),'I am unsure how to begin');
  expect(screen.queryByText(/Trainer preview:/)).toBeNull();
  await user.click(choice);
  expect(screen.getByText(/Trainer preview: i am unsure how to begin/)).toBeTruthy();
  await user.click(choice);
  expect(screen.queryByText(/Trainer preview:/)).toBeNull();
});
it('supports keyboard movement through all six journey stages', async () => {
  const user=userEvent.setup();
  render(<JourneyExplorer />);
  const prepare=screen.getByRole('tab',{name:/Prepare/});
  prepare.focus();
  await user.keyboard('{ArrowRight}');
  expect(screen.getByRole('tab',{name:/Live/}).getAttribute('aria-selected')).toBe('true');
  await user.keyboard('{End}');
  expect(screen.getByRole('tab',{name:/Continue/}).getAttribute('aria-selected')).toBe('true');
  await user.keyboard('{Home}');
  expect(prepare.getAttribute('aria-selected')).toBe('true');
});
it('validates custom annual inputs without showing stale results', async () => {
  const user=userEvent.setup();
  render(<AnnualCalculator />);
  await user.click(screen.getByRole('button',{name:'20%'}));
  await user.click(screen.getByRole('button',{name:'£100'}));
  expect(screen.getByText('£100,000', {selector: '.result-number'})).toBeTruthy();
  await user.clear(screen.getByLabelText('Annual learner base'));
  expect(screen.getByRole('alert').textContent).toContain('Enter a whole learner base');
  expect(screen.queryByText('£100,000', {selector: '.result-number'})).toBeNull();
  await user.click(screen.getByRole('button',{name:/Reset/}));
  expect(screen.getByText('£25,000', {selector: '.result-number'})).toBeTruthy();
});
it('retains the published-tariff qualification when booking assumptions change', async () => {
  const user=userEvent.setup();
  render(<BookingCalculator />);
  await user.selectOptions(screen.getByLabelText('Base booking example'),'3750');
  await user.click(screen.getByRole('button',{name:'£100'}));
  expect(screen.getByText('£4,550')).toBeTruthy();
  expect(screen.getByText('21.3%')).toBeTruthy();
  expect(screen.getByText(/pairs £3,750 with maximum ten/)).toBeTruthy();
  await user.selectOptions(screen.getByLabelText('Participants'),'4');
  expect(screen.getByText('£4,150')).toBeTruthy();
  expect(screen.getByText('10.7%')).toBeTruthy();
});
it('switches the company example without exposing Sarah’s personal development notes', async () => {
  const user=userEvent.setup();
  render(<LearnerPlatform />);
  expect(screen.getByText('Opening conversations clearly')).toBeTruthy();
  await user.click(screen.getByRole('tab',{name:'Company view'}));
  expect(screen.queryByText('Opening conversations clearly')).toBeNull();
  expect(screen.getByText('Journey activated')).toBeTruthy();
  expect(screen.getByText(/not shown to the employer by default/)).toBeTruthy();
});
it('compares the demo and working-pilot scopes while keeping both estimates visible', async () => {
  const user=userEvent.setup();
  render(<NextSteps />);
  expect(screen.getByText('£2,500–£3,500')).toBeTruthy();
  expect(screen.getByText('2–3 weeks')).toBeTruthy();
  expect(screen.getByText('£7,500–£12,000')).toBeTruthy();
  expect(screen.getByText('Around 2 months')).toBeTruthy();
  expect(screen.getByRole('tabpanel').textContent).toContain('not a live learner service');
  const demo=screen.getByRole('tab',{name:/Concept demo/});
  demo.focus();
  await user.keyboard('{ArrowRight}');
  expect(screen.getByRole('tab',{name:/Working pilot/}).getAttribute('aria-selected')).toBe('true');
  expect(screen.getByRole('tabpanel').textContent).toContain('30–50 learners');
  expect(screen.getByRole('tabpanel').textContent).toContain('One live AI roleplay');
  expect(screen.getByText('£2,500–£3,500')).toBeTruthy();
  await user.click(demo);
  expect(screen.getByRole('tabpanel').textContent).toContain('scripted roleplay');
  expect(screen.getByRole('tabpanel').textContent).not.toContain('30–50 learners');
  expect(screen.getByText('Refine, extend or stop.')).toBeTruthy();
  expect(screen.queryByText(/£20k|£35k|£1,000–£2,500/)).toBeNull();
});
it('filters company participation across programmes without treating enrolments as unique learners', async () => {
  const user=userEvent.setup();
  render(<LearnerPlatform />);
  await user.click(screen.getByRole('tab',{name:'Company view'}));
  expect(screen.getByText('32')).toBeTruthy();
  expect(screen.getByText(/not unique people/)).toBeTruthy();
  await user.selectOptions(screen.getByLabelText('Programme'),'conversations');
  expect(screen.getByText('20')).toBeTruthy();
  expect(screen.getByText('18')).toBeTruthy();
  await user.selectOptions(screen.getByLabelText('Programme'),'presentations');
  expect(screen.getByText('12')).toBeTruthy();
  expect(screen.getByText('11')).toBeTruthy();
  expect(screen.queryByText('Opening conversations clearly')).toBeNull();
  await user.click(screen.getByRole('tab',{name:'Training team'}));
  expect(screen.getByText('Awaiting trainer approval')).toBeTruthy();
  expect(screen.getByText(/appropriately shared learner context/)).toBeTruthy();
});
it('previews AI formats without implying live generation or automatic instructor cloning', async () => {
  const user=userEvent.setup();
  render(<JourneyExplorer />);
  await user.click(screen.getByRole('tab',{name:/Practise/}));
  await user.click(screen.getByText('AI persona, avatar & voice options'));
  const options=within(screen.getByRole('group',{name:'Proposed AI interaction format'}));
  await user.click(options.getByRole('button',{name:'Avatar'}));
  expect(screen.getByRole('status').textContent).toContain('explicit permission');
  expect(screen.getByText(/no live AI, generated speech or avatar video/)).toBeTruthy();
  await user.click(options.getByRole('button',{name:'Text'}));
  expect(screen.getByRole('status').textContent).toContain('Type naturally');
});
it('opens qualified evidence and searches the shared source register', async () => {
  const user=userEvent.setup();
  render(<SourceProvider><SourceButton id="S06" /><SourcesButton /></SourceProvider>);
  await user.click(screen.getByRole('button',{name:/View source:/}));
  const dialog=screen.getByRole('dialog');
  expect(within(dialog).getByText(/retrospective LinkedIn post mentions 4,100/)).toBeTruthy();
  expect(within(dialog).getByRole('link',{name:/Read original source/}).getAttribute('rel')).toBe('noreferrer');
  await user.click(screen.getByRole('button',{name:'All sources'}));
  await user.type(screen.getByRole('searchbox',{name:'Search sources'}),'nonsense987');
  expect(screen.getByRole('status').textContent).toContain('No matching sources');
  await user.clear(screen.getByRole('searchbox',{name:'Search sources'}));
  await user.type(screen.getByRole('searchbox',{name:'Search sources'}),'Indicative demo');
  expect(within(dialog).getByRole('button',{name:/Indicative demo and pilot/})).toBeTruthy();
  await user.click(screen.getByRole('button',{name:'Close sources'}));
  expect(screen.queryByRole('dialog')).toBeNull();
});
