'use client';

import { useState } from 'react';
import { ArrowDown, ArrowRight, RotateCcw } from 'lucide-react';
import { annualScenario, bookingScenario, money, number } from '@/lib/calculations';
import { SourceButton } from './sources';
import { Segmented } from './journey';

export function AnnualCalculator() {
  const [base, setBase] = useState('5000');
  const [adoption, setAdoption] = useState(10);
  const [price, setPrice] = useState('50');
  const result = base.trim() && price.trim() ? annualScenario(Number(base), adoption, Number(price)) : null;
  return <div className="annual-calculator">
    <div className="calculator-controls"><div className="calculator-title"><span className="eyebrow">Explore the assumptions</span><button className="text-link" onClick={() => { setBase('5000'); setAdoption(10); setPrice('50'); }}><RotateCcw size={14} />Reset</button></div>
      <div className="calculator-field"><label htmlFor="annual-base">Annual learner base</label><div className="number-field"><input id="annual-base" type="number" inputMode="numeric" min="0" max="1000000" step="1" value={base} onChange={e => setBase(e.target.value)} aria-describedby="base-note" /><span>learners</span></div><p id="base-note" className="micro">Impact Factory states 5,000+ people trained annually on LinkedIn. A scale anchor; latest-year volume remains to be confirmed. <SourceButton id="S06" /></p></div>
      <div className="calculator-field"><div className="range-heading"><label htmlFor="adoption">Assumed adoption</label><output htmlFor="adoption">{adoption}%</output></div><Segmented options={['10%', '20%', '30%']} value={`${adoption}%`} onChange={v => setAdoption(parseInt(v))} label="Adoption presets" /><input id="adoption" type="range" min="0" max="100" value={adoption} onChange={e => setAdoption(Number(e.target.value))} /><div className="range-labels"><span>0%</span><span>Custom adoption</span><span>100%</span></div></div>
      <div className="calculator-field"><label htmlFor="extension-price">Assumed digital extension price</label><Segmented options={['£50', '£100', '£200']} value={`£${price}`} onChange={v => setPrice(v.slice(1))} label="Extension price presets" /><div className="number-field"><span>£</span><input id="extension-price" type="number" inputMode="decimal" min="0" max="10000" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /><span>/ learner</span></div><p className="micro">An assumed sales price, not tested willingness to pay.</p></div>
    </div>
    <div className="calculator-result"><span className="eyebrow">Illustrative annual gross sales</span><div className="result-live" aria-live="polite" aria-atomic="true">{result ? <><strong className="result-number">{money(result.sales)}</strong><div className="result-equation"><span>{number(Number(base))} learners</span><span>×</span><span>{adoption}% adoption</span><span>×</span><span>{money(Number(price))}</span></div><div className="result-divider" /><p className="result-narrative">At this adoption and price, the illustrative gross-sales opportunity would be <strong>{money(result.sales)}</strong>, across <strong>{number(result.learners)}</strong> learner{Number.isInteger(result.learners) ? 's' : '-equivalents'}.</p></> : <><strong className="result-number">—</strong><p role="alert">Enter a whole learner base from 0–1,000,000 and a price from £0–£10,000.</p></>}</div><span className="assumption-tag">Scenario, not a forecast</span><p className="micro">One extension per adopted learner. No historic delegate sales assumed. Repeat attendees would need to be deduplicated.</p><SourceButton id="C01">Calculation assumptions</SourceButton></div>
    <div className="calculator-notice"><strong>Illustrative gross sales scenario, not a forecast.</strong><p>Excludes VAT, discounts, technology costs, implementation costs, customer adoption uncertainty and other operating expenses. Churn and unconfirmed eligibility are also excluded. Gross sales are not profit or ROI.</p></div>
    <details className="scenario-table"><summary>Compare the nine original scenarios <ArrowDown size={16} /></summary><div className="table-scroll"><table><caption>Illustrative gross sales at a 5,000-learner base</caption><thead><tr><th>Adoption</th><th>Learners</th><th>£50</th><th>£100</th><th>£200</th></tr></thead><tbody>{[10,20,30].map(a => <tr key={a}><th>{a}%</th><td>{number(5000*a/100)}</td>{[50,100,200].map(p => <td key={p}>{money(5000*a/100*p)}</td>)}</tr>)}</tbody></table></div></details>
  </div>;
}

export function BookingCalculator() {
  const [base, setBase] = useState(3500);
  const [price, setPrice] = useState('£50');
  const [participants, setParticipants] = useState(8);
  const result = bookingScenario(base, participants, Number(price.slice(1)))!;
  return <div className="booking-calculator"><div className="booking-intro"><span className="eyebrow">A closer view</span><h3>What could it add<br />to one booking?</h3><p>An optional per-person extension around an existing one-day private programme.</p><SourceButton id="S12">Published pricing & qualification</SourceButton></div><div className="booking-controls"><label className="field-label" htmlFor="booking-base">Base booking example</label><select id="booking-base" value={base} onChange={e => setBase(Number(e.target.value))}><option value={3500}>£3,500 — published maximum-eight option</option><option value={3750}>£3,750 — requested eight-attendee illustration</option></select><p className="micro">{base === 3500 ? 'Published form comparison; current quote to confirm.' : 'Assumed example. The form pairs £3,750 with maximum ten, not eight.'} Excludes VAT.</p><div className="booking-input-row"><div><label className="field-label">Digital extension</label><Segmented options={['£50','£100']} value={price} onChange={setPrice} label="Booking add-on price per person" /></div><div><label className="field-label" htmlFor="booking-people">Participants</label><select id="booking-people" value={participants} onChange={e => setParticipants(Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n => <option key={n} value={n}>{n} people</option>)}</select></div></div><div className="booking-result" aria-live="polite" aria-atomic="true"><span>{participants} × {price} = <strong>{money(result.addition)}</strong></span><div><span>{money(base)}</span><ArrowRight size={23} /><strong>{money(result.total)}</strong></div><p><strong>{result.uplift.toFixed(1)}%</strong> illustrative gross booking-value increase</p></div><p className="micro">Illustrative only; willingness to pay and current quote unconfirmed. The base booking stays fixed when participation changes. Added delivery costs are excluded.</p><SourceButton id="C02">How this is calculated</SourceButton></div></div>;
}
