'use client';
import { useState } from 'react';
import { ArrowRight, RotateCcw } from 'lucide-react';
import { annualScenario, bookingScenario, money, number } from '@/lib/calculations';
import { SourceButton } from './sources';
import { Disclosure, Select, Segmented, TabBar } from './ui';

export function CommercialScenarios() {
  const [view, setView] = useState('annual');
  return <section className="commercial-scenarios" aria-labelledby="scenarios-title"><div className="section-topline"><div><span className="eyebrow">Illustrative calculations</span><h2 id="scenarios-title">What the assumptions add up to</h2></div><TabBar id="economics" label="Commercial scenarios" items={[{value:'annual',label:'Annual scale'},{value:'booking',label:'One booking'}]} value={view} onChange={setView} /></div><div id="economics-panel" role="tabpanel" aria-labelledby={'economics-' + view}>{view === 'annual' ? <AnnualCalculator /> : <BookingCalculator />}</div></section>;
}
export function AnnualCalculator() {
  const [base, setBase] = useState('5000');
  const [adoption, setAdoption] = useState(10);
  const [price, setPrice] = useState('50');
  const result = base.trim() && price.trim() ? annualScenario(Number(base), adoption, Number(price)) : null;
  return <div className="annual-calculator">
    <div className="calculator-layout"><div className="calculator-controls">
      <div className="calculator-field"><label htmlFor="annual-base">Annual learner base</label><div className="number-field"><input id="annual-base" type="number" inputMode="numeric" min="0" max="1000000" step="1" value={base} onChange={e => setBase(e.target.value)} aria-invalid={base.trim() === '' || !Number.isInteger(Number(base)) || Number(base) < 0 || Number(base) > 1000000} aria-describedby={result ? 'base-note' : 'base-note calculator-error'} /><span>learners</span></div><p id="base-note" className="micro">5,000+ is a LinkedIn scale claim; actual annual volume needs confirmation. <SourceButton id="S06">Source</SourceButton></p></div>
      <div className="calculator-field"><div className="range-heading"><label htmlFor="adoption">Assumed adoption</label><output htmlFor="adoption">{adoption}%</output></div><Segmented options={['10%','20%','30%']} value={adoption+'%'} onChange={v => setAdoption(parseInt(v))} label="Adoption presets" /><input id="adoption" type="range" min="0" max="100" value={adoption} onChange={e => setAdoption(Number(e.target.value))} /><div className="range-labels"><span>0%</span><span>100%</span></div></div>
      <div className="calculator-field"><label htmlFor="extension-price">Assumed extension price</label><div className="price-inputs"><Segmented options={['£50','£100','£200']} value={'£'+price} onChange={v => setPrice(v.slice(1))} label="Extension price presets" /><div className="number-field"><span>£</span><input id="extension-price" type="number" inputMode="decimal" min="0" max="10000" step="0.01" value={price} onChange={e => setPrice(e.target.value)} aria-invalid={price.trim() === '' || !Number.isFinite(Number(price)) || Number(price) < 0 || Number(price) > 10000} aria-describedby={result ? undefined : 'calculator-error'} /></div></div><p className="micro">Per learner. Willingness to pay has not been tested.</p></div>
    </div><div className="calculator-result"><span className="eyebrow">Illustrative annual gross sales</span><div className="result-live" aria-live="polite" aria-atomic="true">{result ? <><strong className={'result-number' + (money(result.sales).length > 9 ? ' long-result' : '')}>{money(result.sales)}</strong><div className="result-equation"><span>{number(Number(base))} learners</span><span>× {adoption}% adoption</span><span>× {money(Number(price))} per learner</span></div><p>Across <strong>{number(result.learners)}</strong> {Number.isInteger(result.learners) ? 'learners' : 'learner-equivalents'}, with one extension each.</p></> : <><strong className="result-number">—</strong><p id="calculator-error" role="alert">Enter a whole learner base from 0–1,000,000 and a price from £0–£10,000.</p></>}</div><div className="calculator-result-bottom"><SourceButton id="C01">Assumptions</SourceButton><button className="text-link" onClick={() => { setBase('5000'); setAdoption(10); setPrice('50'); }}><RotateCcw size={14} />Reset</button></div></div></div>
    <p className="calculator-notice"><strong>Illustrative gross-sales scenarios only, not forecasts.</strong> Excludes VAT, discounts, implementation, technology costs, operating expenses, churn and uncertainty around customer adoption. Gross sales are not profit.</p>
    <Disclosure title="Compare all nine scenarios"><div className="table-scroll"><table><caption>Illustrative gross sales at a 5,000-learner scale</caption><thead><tr><th>Adoption</th><th>Learners</th><th>£50</th><th>£100</th><th>£200</th></tr></thead><tbody>{[10,20,30].map(a => <tr key={a}><th>{a}%</th><td>{number(5000*a/100)}</td>{[50,100,200].map(p => <td key={p}>{money(5000*a/100*p)}</td>)}</tr>)}</tbody></table></div></Disclosure>
  </div>;
}
export function BookingCalculator() {
  const [base, setBase] = useState(3500);
  const [price, setPrice] = useState('£50');
  const [participants, setParticipants] = useState(8);
  const result = bookingScenario(base, participants, Number(price.slice(1)))!;
  return <div className="booking-calculator"><div className="calculator-layout"><div className="calculator-controls">
    <div className="calculator-field"><label htmlFor="booking-base">Base booking example</label><Select id="booking-base" value={base} onChange={e => setBase(Number(e.target.value))}><option value={3500}>£3,500 · up to 8 delegates</option><option value={3750}>£3,750 · assumed 8 attendees</option></Select><p className="micro">{base === 3500 ? 'Published maximum-eight option; current quote to confirm.' : 'Assumed example. The form pairs £3,750 with maximum ten, not eight.'} Excludes VAT. <SourceButton id="S12">Published pricing</SourceButton></p></div>
    <div className="calculator-field"><span className="field-label">Extension price per person</span><Segmented options={['£50','£100']} value={price} onChange={setPrice} label="Booking add-on price per person" /></div>
    <div className="calculator-field"><label htmlFor="booking-people">Participants</label><Select id="booking-people" value={participants} onChange={e => setParticipants(Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n => <option key={n} value={n}>{n} {n === 1 ? 'person' : 'people'}</option>)}</Select><p className="micro">The base booking stays fixed as attendance changes.</p></div>
  </div><div className="calculator-result booking-result" aria-live="polite" aria-atomic="true"><span className="eyebrow">Illustrative booking value</span><div className="booking-change"><span>{money(base)}</span><ArrowRight size={22} /><strong>{money(result.total)}</strong></div><div className="booking-addition">{participants} × {price} = <strong>{money(result.addition)}</strong> added</div><div className="booking-uplift"><strong>{result.uplift.toFixed(1)}%</strong><span>gross booking-value increase</span></div><SourceButton id="C02">Calculation assumptions</SourceButton></div></div><p className="calculator-notice"><strong>Illustrative only.</strong> These are assumed add-on prices, with no evidence that clients would pay them. Excludes VAT and additional delivery costs; this is not a margin or ROI calculation.</p></div>;
}
