'use client';
import { useState } from 'react';
import { Check, LockKeyhole } from 'lucide-react';
import { Disclosure, Select, TabBar } from './ui';
import { SourceButton } from './sources';

const courses = [
  {id:'conversations',name:'Difficult Conversations',booked:20,attended:18,activated:15,reinforced:12,practised:9},
  {id:'presentations',name:'Presentation Skills',booked:12,attended:11,activated:10,reinforced:8,practised:6},
];
export function LearnerPlatform() {
  const [view, setView] = useState('learner');
  const [course, setCourse] = useState('all');
  const selected = courses.filter(c => course === 'all' || course === c.id);
  const totals = selected.reduce((sum,c) => ({booked:sum.booked+c.booked,attended:sum.attended+c.attended,activated:sum.activated+c.activated,reinforced:sum.reinforced+c.reinforced,practised:sum.practised+c.practised}),{booked:0,attended:0,activated:0,reinforced:0,practised:0});
  return <>
    <ol className="lms-flow" aria-label="Proposed learning platform flow">{[['Enrol','Join a course or company cohort'],['Prepare & attend','Bring context to the live session'],['Revisit & practise','Receive relevant follow-up'],['Review & continue','Return to a trainer or another course']].map(([title,detail],i) => <li key={title}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{title}</strong><p>{detail}</p></div></li>)}</ol>
    <div className="platform-toolbar"><TabBar id="platform" label="Platform views" items={[{value:'learner',label:'Learner view'},{value:'company',label:'Company view'},{value:'team',label:'Training team'}]} value={view} onChange={setView} /><span className="concept-label">Switch views · Fictional LMS example</span></div>
    <div id="platform-panel" role="tabpanel" aria-labelledby={'platform-' + view} className="platform-panel">
      {view === 'learner' && <><div className="record-header"><span className="avatar">SM</span><div><h2>Sarah Mitchell</h2><p>Northstar Ltd · My learning</p></div><span className="record-status">One account across courses</span></div>
        <div className="record-body"><div><span className="eyebrow">My programmes</span><div className="course-card"><span className="course-state">In progress</span><h3>Difficult Conversations</h3><p>Preparation → live training → follow-up</p><ul className="record-checklist">{[['Live programme','Attended'],['Two reinforcement activities','Complete'],['Practice · receptive scenario','Complete'],['Practice · defensive scenario','Next']].map(([label,status],i) => <li key={label}>{i<3 ? <span className="check-circle"><Check size={13} /></span> : <span className="empty-circle" />}<span>{label}</span><small>{status}</small></li>)}</ul></div><div className="course-mini"><div><strong>Presentation Skills</strong><span>Another course in Sarah’s company programme</span></div><span className="course-state">Upcoming</span></div></div>
        <div className="learner-focus"><span className="eyebrow">My next activity</span><h3>Opening conversations clearly</h3><p>Try a defensive conversation, building on the receptive scenario already completed.</p><div className="next-activity"><span className="eyebrow">One place to return to</span><strong>Courses, resources & personal progress</strong><p>Find approved videos, lessons, practice and trainer follow-up without searching through old emails.</p></div></div></div>
      </>}
      {view === 'company' && <><div className="record-header"><span className="avatar company-avatar">N</span><div><h2>Northstar Ltd</h2><p>Company learning overview</p></div><div className="company-filter"><label htmlFor="company-course">Programme</label><Select id="company-course" value={course} onChange={e => setCourse(e.target.value)}><option value="all">All programmes</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></div></div>
        <div className="company-body"><div className="company-totals"><div><strong>{totals.booked}</strong><span>Course enrolments</span></div><div><strong>{totals.attended}</strong><span>Training attendances</span></div><p>{course==='all' ? 'Across two fictional programmes. A person on both courses is counted twice; these are not unique people.' : 'Programme participation across suitable small cohorts.'}</p></div><div className="participation-rows"><span className="eyebrow">Continued engagement</span>{[['Journey activated',totals.activated],['Reinforcement completed',totals.reinforced],['Practice completed',totals.practised]].map(([label,count]) => <div className="participation-row" key={label}><div><span>{label}</span><strong>{count}<small> / {totals.booked}</small></strong></div><div className="participation-track" aria-hidden="true"><span style={{width:Number(count)/totals.booked*100+'%'}} /></div></div>)}<p className="micro">Denominator: {totals.booked} course enrolments. Participation is not proof of competence.</p></div></div>
      </>}
      {view === 'team' && <><div className="record-header"><span className="avatar">IF</span><div><h2>Impact Factory training team</h2><p>Programme oversight · proposed workspace</p></div><span className="record-status">Human approval stays central</span></div><div className="team-workspace"><div><span className="eyebrow">Before the live session</span><h3>See the context learners choose to share.</h3><p>Review goals and preparation by course or cohort. Use that context to shape the conversation in the room.</p></div><div><span className="eyebrow">After the live session</span><ul className="team-queue"><li><strong>Recap video</strong><span>Awaiting trainer approval</span></li><li><strong>Personalised follow-up</strong><span>Review before scheduling</span></li><li><strong>Practice scenario</strong><span>Approved version ready</span></li></ul><p className="micro">Illustrative workflow statuses, not an active queue.</p></div></div></>}
      <div className="record-privacy"><LockKeyhole size={15} /><span>{view==='company' ? 'Private conversations and individual AI assessments are not shown to the employer by default.' : view==='team' ? 'Trainer access is limited to agreed roles and appropriately shared learner context.' : 'Personal reflections and conversations would have clear sharing choices.'}</span></div>
    </div>
    <section className="lms-benefits" aria-label="Value across the course portfolio"><div><h3>For learners</h3><p>One familiar home for every enrolled course, with a clear next activity.</p></div><div><h3>For company / L&D</h3><p>A view across programmes, cohorts and participation to support development planning.</p></div><div><h3>For Impact Factory</h3><p>Reusable course journeys, approved content and a direct route back to learners.</p></div></section>
    <Disclosure title="What the lightweight LMS could include"><div className="lms-feature-grid"><div><strong>Courses & enrolment</strong><p>A course catalogue, company workspaces, cohort invitations and access to enrolled programmes.</p></div><div><strong>Learning & follow-up</strong><p>Preparation, live-session details, videos, personalised lessons, reminders and AI practice.</p></div><div><strong>Progress & oversight</strong><p>Attendance, activity completion, approved content versions and permissioned reporting by course or company.</p></div></div><p>Company and public-course learners could use the same hub. Each person sees the courses they are enrolled in; client agreements determine access.</p><p>Start with one programme. Add further courses only after testing the journey and the team’s workload. Existing booking and HubSpot workflows could connect where useful.</p><SourceButton id="P02">Concept assumptions</SourceButton></Disclosure>
    <p className="page-footnote">The starting idea is a branded hub built on a suitable LMS. Pilot design would check ease of use, company separation, connections to existing tools and running costs. No vendor is selected.</p>
  </>;
}
