import { ArrowDown, ArrowRight, ArrowUpRight, Check, HeartHandshake, Plus, Users } from 'lucide-react';
import { Navigation } from './navigation';
import { SourceButton, SourceProvider, SourcesSection } from './sources';
import { CurrentJourney, JourneyExplorer } from './journey';
import { CompanyDashboard, DiscussionChecklist, LearnerProfile, PilotDetails } from './illustrations';
import { AnnualCalculator, BookingCalculator } from './calculators';

function SectionHeading({ number, label, title, description }: { number: string; label: string; title: React.ReactNode; description?: string }) {
  return <div className="section-heading"><div className="section-index"><span>{number}</span><span>{label}</span></div><div><h2>{title}</h2>{description && <p className="section-description">{description}</p>}</div></div>;
}
const heard = [
  { num: '01', title: 'A strong human experience', text: 'Small groups, trainer expertise, practical exercises and individual attention are the heart of the offer.', tag: 'The strength to preserve' },
  { num: '02', title: 'A fragmented digital journey', text: 'Resources, email, HubSpot and personal follow-up already support learners. They are not yet one connected journey.', tag: 'The continuity to explore' },
  { num: '03', title: 'Tailored work matters', text: 'Taylor estimates that approximately 60–70% of revenue comes from tailored work. Corporate delivery deserves particular attention.', tag: 'Discovery estimate · not audited data' },
  { num: '04', title: 'A learner touchpoint can fade', text: 'Resources may go through a booking manager, leaving Impact Factory one step removed from the people who attended.', tag: 'The relationship to maintain' },
];
const mechanisms = [
  { title: 'Extend the relationship', description: 'From a training day into a useful 30, 60 or 90-day learning journey.', number: '01' },
  { title: 'Strengthen the corporate proposition', description: 'A coherent combination of live learning, reinforcement and practice for L&D to consider.', number: '02' },
  { title: 'Explore a premium add-on', description: 'A defined digital extension alongside existing programmes, if customers see value in it.', number: '03' },
  { title: 'Keep the learner touchpoint', description: 'A direct, agreed connection with delegates, especially where the buyer sits between them and Impact Factory.', number: '04' },
];

export default function Proposal() {
  return <SourceProvider><a href="#main-content" className="skip-link">Skip to proposal</a><Navigation /><main id="main-content">
    <section className="hero section-container" id="overview" aria-labelledby="hero-title">
      <div className="hero-topline"><span className="eyebrow"><span className="small-orange-line" />A conversation, continued</span><span className="edition">September 2026 <span> / </span> Working paper 01</span></div>
      <div className="hero-layout"><div><p className="hero-context">Based on conversations with Abigail and Taylor</p><h1 id="hero-title">Extending the<br className="desktop-break" /> learning journey<br /><em>beyond the room.</em></h1><p className="hero-support">One possible digital layer around Impact Factory’s human-led training — helping learners prepare, remember, practise and apply what they learn.</p><a href="#journey" className="hero-link">Explore the possible journey <ArrowDown size={18} /></a></div><aside className="hero-note"><span className="note-number">A simple starting point</span><div className="note-rule" /><p>The human experience<br />stays at the centre.</p><span>Technology helps the learning<br />continue around it.</span><div className="hero-note-bottom"><HeartHandshake size={25} strokeWidth={1.3} /><span>Impact Factory expertise,<br />supported by technology</span></div></aside></div>
      <div className="hero-journey" aria-label="Prepare, live human-led training, remember, practise, apply"><div><span className="journey-dot" /><strong>Prepare</strong><span>Before the room</span></div><div className="hero-live"><span className="journey-dot"><Users size={18} /></span><strong>Live</strong><span>Human-led Impact Factory training</span></div><div><span className="journey-dot" /><strong>Remember</strong><span>Bring it back</span></div><div><span className="journey-dot" /><strong>Practise</strong><span>Try it safely</span></div><div><span className="journey-dot" /><strong>Apply</strong><span>Use it at work</span></div></div>
      <div className="hero-bottom"><span>A proposal for discussion, not a finished product.</span><a href="#pilot">Start with one programme <ArrowRight size={14} /></a></div>
    </section>
    <section className="section section-container" id="what-we-heard" aria-labelledby="heard-title"><SectionHeading number="01" label="Our understanding" title={<span id="heard-title">Build around what<br />already makes it work.</span>} description="The discovery conversations point to a natural extension of the experience people already value." /><div className="heard-grid">{heard.map(item => <article className="heard-card" key={item.num}><span className="card-number">{item.num}</span><h3>{item.title}</h3><p>{item.text}</p><span className="card-tag">{item.tag}</span></article>)}</div><div className="section-source"><span>From the discovery conversations.</span><SourceButton id="D01">Read the discovery basis</SourceButton></div><div className="why-statement"><span className="eyebrow">Why this matters</span><p>Maintain the learner relationship<br /><em>around the workshop.</em></p><span>The live training remains the centre of the experience.</span></div><CurrentJourney /></section>
    <section className="scale-section" id="business-today" aria-labelledby="scale-title"><div className="section-container"><div className="scale-heading"><span className="eyebrow">Impact Factory today</span><h2 id="scale-title">An established business.<br />A personal way of learning.</h2><SourceButton id="S01">Published business anchors</SourceButton></div><div className="scale-grid">{[['175,000+','historical delegates','S01'],['13,000','companies impacted','S01'],['50+','countries worked in','S01'],['35','years of experience','S01'],['5,000+','people trained annually¹','S06']].map(([value,label,id]) => <div className="scale-stat" key={value}><strong>{value}</strong><span>{label}</span><SourceButton id={id}>{id === 'S06' ? 'LinkedIn' : 'Official website'}</SourceButton></div>)}</div><div className="scale-footnotes"><p><strong>Small groups, generally 6–8 delegates.</strong> Individual attention is part of the public offer. <SourceButton id="S03" /></p><p>¹ LinkedIn profile claim; used as a scale anchor. A retrospective post reports 4,100 individuals, so actual annual volume needs reconciling. Figures checked 25 September 2026. <SourceButton id="S07">Qualification</SourceButton></p></div></div></section>
    <section className="section section-container journey-section" id="journey" aria-labelledby="journey-title"><SectionHeading number="02" label="One possible future" title={<span id="journey-title">A little before.<br />A little after.<em> A lasting connection.</em></span>} description="Select a stage to explore how the digital layer could support a Difficult Conversations programme. The examples are interactive; the learning approach stays human-led." /><JourneyExplorer /></section>
    <section className="section section-container profile-section" id="platform" aria-labelledby="profile-title"><SectionHeading number="03" label="The connecting layer" title={<span id="profile-title">Remember the learner.<br /><em>Not just the booking.</em></span>} description="A lightweight learner record could connect the company, programme, training date, goals, activities, practice and next useful step." /><LearnerProfile /><div className="profile-comparison"><div><span className="eyebrow">When follow-up is disconnected</span><p>The next message may be the same for everyone, regardless of what they tried.</p></div><ArrowRight size={24} className="comparison-arrow" /><div><span className="eyebrow">With a connected learner record</span><p>The next interaction can respond to what someone has actually completed, practised and chosen.</p></div></div><p className="micro">Use the existing booking and HubSpot processes where they work. Start with a minimal record; integrations and persistent coaching context are later scope decisions.</p></section>
    <section className="section-tint" id="company-view" aria-labelledby="company-title"><div className="section section-container"><SectionHeading number="04" label="The corporate relationship" title={<span id="company-title">A useful view for L&D.<br /><em>A private space for learners.</em></span>} description="Help the buyer coordinate bookings and see participation across a programme, while keeping personal rehearsal and sensitive conversations private." /><CompanyDashboard /></div></section>
    <section className="section section-container" id="business-case" aria-labelledby="business-title"><SectionHeading number="05" label="An opportunity worth testing" title={<span id="business-title">What could this add<br />to the business?</span>} description="Four plausible mechanisms to explore. Their value would need to be tested with learners, trainers and clients." /><div className="mechanism-grid">{mechanisms.map(m => <article key={m.number}><span className="card-number">{m.number}</span><h3>{m.title}</h3><p>{m.description}</p></article>)}</div><div className="calculator-heading"><div><span className="eyebrow">Illustrative scenario</span><h3>Explore the scale.<br /><em>Keep the assumptions visible.</em></h3></div><p>Change adoption and price to see the arithmetic. These inputs do not predict customer demand.</p></div><AnnualCalculator /><div id="booking-economics"><BookingCalculator /></div><p className="business-cost-note">The customer add-on prices above are hypothetical sales prices. The technology ranges below would be a cost to Impact Factory. Content review, support, usage and operating costs would need to be measured before any margin decision.</p></section>
    <section className="section section-container evidence-section" id="learning-design" aria-labelledby="evidence-title"><SectionHeading number="06" label="The learning logic" title={<span id="evidence-title">Active learning.<br /><em>A reasoned starting point.</em></span>} description="The proposed design is consistent with established evidence favouring active practice, retrieval and feedback." /><div className="evidence-grid"><article className="evidence-card"><span className="eyebrow">Practice & rehearsal</span><strong className="evidence-number">117<span>studies</span></strong><h3>Make practice relevant<br />to the learner’s world.</h3><p>A behaviour-modelling meta-analysis associated stronger transfer with practice using trainee-generated scenarios, alongside other design and workplace conditions.</p><div className="evidence-citation"><span>Taylor, Russ-Eft & Chan · 2005</span><SourceButton id="S14">Research</SourceButton></div></article><article className="evidence-card"><span className="eyebrow">Retrieval & application</span><strong className="evidence-number">122<span>experiments · 10,382 participants</span></strong><h3>Ask someone to retrieve<br />and use an idea.</h3><p>A retrieval-practice meta-analysis found transferable learning benefits, with results varying by task and retrieval conditions.</p><div className="evidence-citation"><span>Pan & Rickard · 2018</span><SourceButton id="S15">Research</SourceButton></div></article></div><div className="evidence-boundary"><p><strong>This supports the design logic, not a product-effectiveness claim.</strong> These studies do not prove the proposed experience will work. Feedback quality matters too; information content and context affect its usefulness. <SourceButton id="S16">Feedback evidence</SourceButton></p></div></section>
    <section className="section section-container" id="pilot" aria-labelledby="pilot-title"><SectionHeading number="07" label="A phased way to explore this" title={<span id="pilot-title">Start small.<br /><em>Learn before committing.</em></span>} description="Choose one real programme and find out whether the experience is useful, trusted and manageable to run." /><div className="pilot-card"><div className="pilot-card-title"><div><span className="eyebrow">Recommended starting programme</span><h3>Difficult Conversations</h3></div><span className="pilot-stamp">One programme<br />One learner journey</span></div><div className="pilot-sequence"><span>Design together</span><ArrowRight size={17} /><span>Try with learners</span><ArrowRight size={17} /><span>Review the evidence</span></div><PilotDetails /><div className="pilot-footer"><HeartHandshake size={20} /><p>Trainer review throughout. No larger platform commitment before the evidence review.</p></div></div></section>
    <section className="section section-container operations-section" id="operating-model" aria-labelledby="operations-title"><SectionHeading number="08" label="Make it workable" title={<span id="operations-title">Preserve the quality.<br /><em>Be clear about the work.</em></span>} description="A managed service could reduce the technology burden. It still needs Impact Factory’s content judgement, quality review and learner care." /><div className="operations-grid"><article><span className="eyebrow">The proposed day-to-day</span><h3>One learning owner.<br />One technical operator.</h3><p>Impact Factory approves the cohort, content and learning decisions. MyPath configures the journey, resolves access problems, monitors usage and maintains the technical service.</p><p>Learning questions return to the Impact Factory contact. Changes to guidance and feedback require trainer approval.</p></article><div className="risk-disclosures">{[
      ['Quality and the human voice','Impact Factory defines criteria and approves content. MyPath tests the roleplay and feedback. Critical quality issues stop release.'],
      ['Permissions and privacy','Agree what learners, trainers and employers can see; minimise data, set retention, and protect small groups. A specific data/privacy review precedes live learner use.'],
      ['Content and integrations','Check content rights. Start with approved resources and a simple roster. Booking sync, Teams and SSO need separate scope decisions.'],
      ['Workload and economics','Record trainer review and support time. Agree response hours, a change allowance, usage caps, an exit route and a total pilot budget before starting.'],
    ].map(([title,text]) => <details key={title}><summary>{title}<Plus size={17} /></summary><p>{text}</p></details>)}</div></div></section>
    <section className="section-tint" id="commercial-options" aria-labelledby="commercial-title"><div className="section section-container"><SectionHeading number="09" label="A possible commercial path" title={<span id="commercial-title">Explore first.<br /><em>Extend when it makes sense.</em></span>} description="Internal working ranges for discussion. Each step depends on what the pilot teaches us; annual options are alternatives, not additive fees." /><div className="commercial-grid">{[
      { n:'01',label:'Explore',title:'Design / prototype pilot',price:'£2k–£3.5k',period:'one-off · indicative',text:'One programme, one journey, one scenario and a small test group.',detail:'Reuse approved material and simple interactions. Prototype depth and a limited usage allowance must be agreed. The larger learner test is separately scoped.' },
      { n:'02',label:'Reinforce',title:'Smart journey layer',price:'£9k–£15k',period:'per year + agreed usage',text:'Preparation, short reinforcement and a connected learner record.',detail:'Scope depends on programmes, active learners, content updates and operating support. Integrations and new content production need an explicit allowance.' },
      { n:'03',label:'Practise',title:'Roleplay capability',price:'£18k–£25k',period:'per year + usage',text:'Bounded practice, separate feedback and agreed quality monitoring.',detail:'Scenarios, text versus voice, session volume, quality evaluation and support determine the final scope. Unlimited practice is not assumed.' },
      { n:'04',label:'Extend',title:'Managed digital coach / platform',price:'£25k–£40k',period:'per year + usage / integrations',text:'Broader continuity, persistent context and managed operations.',detail:'Personalisation, reporting, integrations, service levels and data requirements require scoping. This is a proposed future service, not an existing product claim.' },
    ].map(c => <article key={c.n} className="commercial-card"><span className="card-number">{c.n}</span><h3>{c.label}</h3><p className="commercial-subtitle">{c.title}</p><strong className="commercial-price">{c.price}</strong><span className="micro">{c.period}</span><p>{c.text}</p><details><summary>Scope to agree<Plus size={15} /></summary><p>{c.detail}</p></details></article>)}</div><p className="commercial-notice">Working commercial ranges for discussion only; final pricing depends on scope, infrastructure, number of learners, integrations and support. Indicative, subject to scope. Planning ranges exclude VAT; a final quote must state taxes and all inclusions. <SourceButton id="P01">Assumptions</SourceButton></p></div></section>
    <section className="section section-container" id="partnership" aria-labelledby="partnership-title"><SectionHeading number="10" label="Who does what" title={<span id="partnership-title">Impact Factory leads<br /><em>the learning.</em></span>} /><div className="partnership-grid"><article><span className="eyebrow">Learning expertise & relationships</span><h3>Impact Factory</h3><ul>{['Methodology and programme design','Trainer expertise','Client relationships','Scenarios and approved content','Learning quality control'].map(t => <li key={t}><Check size={17} />{t}</li>)}</ul></article><article><span className="eyebrow">Proposed technology partner</span><h3>MyPath</h3><ul>{['Technology and product engineering','AI infrastructure','Learner journey and platform','Technical operations','Generation tooling, iteration and testing'].map(t => <li key={t}><Check size={17} />{t}</li>)}</ul></article></div><p className="partnership-statement">Impact Factory remains the learning expert.<br /><em>Technology extends its reach.</em></p><p className="micro partnership-note">Proposed responsibilities, subject to scope and capability validation. Impact Factory retains methodology and content approval; ownership, licences, data responsibilities and service exit would be agreed before production.</p></section>
    <section className="closing-section" id="next-decision" aria-labelledby="closing-title"><div className="section-container"><span className="eyebrow">The next sensible step</span><h2 id="closing-title">One programme.<br />One learner journey.<br /><em>Test what creates value.</em></h2><p>Choose one real Impact Factory programme, design a small experience around approved material, and test it before making any larger platform decision.</p><DiscussionChecklist /></div></section>
    <div className="section-container"><SourcesSection /></div>
  </main><footer className="site-footer section-container"><div><a className="wordmark" href="#overview">Impact Factory<span className="wordmark-dot">.</span></a><p>Working proposal prepared following conversations<br />with Abigail Brooks-Daw and Taylor.</p></div><div><span>September 2026 · For discussion</span><span>Technology partnership explored with MyPath</span><a href="#overview">Back to top <ArrowUpRight size={14} /></a></div></footer></SourceProvider>;
}
